# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./samp2_1.h
SOURCES += ./main.cpp \
    ./samp2_1.cpp
FORMS += ./samp2_1.ui
RESOURCES += samp2_1.qrc
